Repository thoth-station/glyph, pull requests merged in 2020-09, with the labels that each got.

#40 Return empty log if no messages are supplied
  thoth/glyph/lib.py
Labels: approved, size/XS

#43 pre-commit related fixes
  thoth/glyph/formatter.py
  thoth/glyph/lib.py
  thoth/glyph/models.py
Labels: size/M

#47 Release of version 0.1.1
  CHANGELOG.md
  thoth/glyph/__init__.py
Labels: approved, bot, size/S

#44 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#49 Fixed empty commit issue
  Pipfile.lock
  thoth/glyph/lib.py
Labels: approved, size/L

#51 Release of version 0.1.2
  CHANGELOG.md
  thoth/glyph/__init__.py
Labels: approved, bot, size/XS

#52 Fix value error
  Pipfile.lock
  README.rst
  thoth/glyph/lib.py
Labels: approved, size/M

#56 Release of version 0.1.3
  CHANGELOG.md
  thoth/glyph/__init__.py
Labels: approved, bot, size/XS

#57 Added release to pypi
  .aicoe-ci.yaml
Labels: approved, size/XS

#59 Adjust logic to use dataframe one and correct method output typing
  thoth/glyph/lib.py
Labels: approved, size/S

#61 Release of version 0.1.4
  CHANGELOG.md
  thoth/glyph/__init__.py
Labels: approved, bot, size/XS
