Repository thoth-station/glyph, pull requests merged in 2020-08, with the labels that each got.

#20 Remove sub-command not used in CLI
  thoth/glyph/cli.py
Labels: approved, size/S

#21 Tushar is code owner
  .github/CODEOWNERS
Labels: approved, size/XS

#23 Minor refactoring of the constants module
  thoth/glyph/constants.py
Labels: approved, size/S

#22 Provide docstrings for exceptions
  thoth/glyph/exceptions.py
Labels: approved, size/XS

#24 Mark static methods
  thoth/glyph/formatter.py
  thoth/glyph/models.py
Labels: approved, size/XS

#25 Remove unused imports
  thoth/glyph/lib.py
  thoth/glyph/models.py
Labels: approved, size/XS

#28 Grouping user-defined commit phrases
  thoth/glyph/lib.py
Labels: approved, size/M

#29 README updated #27
  README.rst
Labels: approved, size/M

#30 Readme updated, minor fix
  README.rst
  thoth/glyph/cli.py
Labels: approved, size/M

#31 Library level exception added to __init__.py
  thoth/glyph/__init__.py
Labels: approved, size/XS

#33 Release of version 0.1.0
  CHANGELOG.md
  thoth/glyph/__init__.py
Labels: approved, bot, size/S

#34 Fix syntax errors in README
  README.rst
Labels: size/M

#35 Fix package description
  setup.py
Labels: approved, size/XS
